server:
  port: @server.port@
  tomcat:
    uri-encoding: UTF-8
  servlet:
    context-path: @server.context-path@

# dubbo消费者配置
dubbo:
  application:
    name: osce-server
    id: osce-server
  registry:
    address: @dubbo.registry.address@
    port: 2181
    file: @dubbo.registry.file@
  protocol:
    name: dubbo
    port: -1
    accesslog: true
  config-center:
    timeout: 60000
  scan:
    base-packages: com.osce

# 验证码配置
imageCode:
  width: 116
  height: 40
  codeLength: 4
  randomString: ABCDEFGHIJKLMNPQRSTUVWXYZ1234567890abcdefghijkmnpqrstuvwxyz
  sessionKey: SESSION_VCODE
  font:
    name: Times New Roman
    style: 0
    size: 36
  expireTime: 600

# 网站配置
website: 
  name: OSCE考试管理系统
  pic:
    uploadType: jpg,jpeg,png
    maxUploadValue: 5120
  audio:
    uploadType: mp3,wav,ogg
    maxUploadValue: 10240
  video:
    uploadType: mp4,avi,wmv,3gp,mkv,f4v,rmvb
    maxUploadValue: 51200
  approve:
  logSwitch: Y
  copyright: 版权所有 Copyright © Since2018 上海嘉奕医学科技有限公司
  ipBlacklist:


spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: non_null
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 1024MB

# oss设置

